export const metadata = {
    title: 'Comprar timbres',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({ children }) {
    return (
      <html lang="es">
        <body>{children}</body>
      </html>
    )
  }
  